" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
  \| endif


call plug#begin()

Plug 'dart-lang/dart-vim-plugin'
Plug 'dense-analysis/ale'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'

call plug#end()


" ale
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_java_javac_classpath = '.'
let g:ale_java_javac_sourcepath = ['.']


" lsp
set signcolumn=no
let g:lsp_buffer_enabled = 1
let g:lsp_diagnostics_enabled = 0
let g:lsp_diagnostics_signs_enabled = 0
let g:lsp_document_highlight_enabled = 0


" 基本設定は上書きされないように最後に読み込む。
inoremap <silent> jj <ESC>
language C
set colorcolumn=80
set expandtab
set hlsearch
set hidden
set number
set showmatch
set shiftwidth=2
set splitright
set tabstop=2
set wildmenu
syntax on

" インデントは基本的にオフにするが、前の行を参照にするという
" シンプルなルールに従う autoindent はコントロールしやすいので有効する。
filetype indent off
set autoindent
