tap "homebrew/bundle"

brew "cask"
brew "flake8"
brew "tmux"

cask "alacritty"
cask "clipy"
cask "google-chrome"
cask "google-drive"
cask "hammerspoon"
cask "macvim"
cask "visual-studio-code"
cask "zoom"
