
# ====================== FONT ========================
[font]

# Offset is extra space around each character
offset = { x = 0, y = 5 }  # Default: x = 0, y = 0


# ====================== WINDOW ======================
[window]

# Startup mode (changes require restart)
startup_mode = "Maximized"  # Default: "Windowed"


# ====================== ENV =========================
[env]
TERM = "xterm-256color"

[general]
# ====================== GENERAL ======================
# Import additional configuration files
import = [
  "~/.config/alacritty/alacritty_local.toml"
]
