[[plugins]]
repo = 'Shougo/unite.vim'


[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']


[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = ['PP', 'PrettyPrint']


[[plugins]]
repo = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui = 1


## Dart
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']


## Java
[[plugins]]
# ref: https://github.com/vim-scripts/vim-javacomplete2
repo = 'artur-shaik/vim-javacomplete2'
on_ft = ['java']
hook_source = '''
  autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''


## JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_source = '''
  let g:javascript_plugin_jsdoc = 1
  let g:javascript_plugin_ngdoc = 1
'''


## Python
[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']
hook_add = '''
  let g:jedi#popup_on_dot = 0
  let g:jedi#goto_command = "<leader>d"
  let g:jedi#goto_assignments_command = "<leader>g"
  let g:jedi#goto_definitions_command = ""
  let g:jedi#documentation_command = "K"
  let g:jedi#usages_command = "<leader>n"
  let g:jedi#rename_command = "<leader>R"
  autocmd FileType python setlocal completeopt-=preview
'''


## TypeScript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
